# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:fMRnHSEd56MR04iEpLiYjYz1pKM=,iv:cLQjycXfYyRnJtz5nohDme3dOIO45K4yuYW18T+daLQ=,tag:51yfIY/wO7zBYvmpPkedcw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:uyLHNxCHQ7U/85nx4Lr/dXdY4LhipyUigweSEkJRIeMjqxrhkA==,iv:ATIx2zaDJegm/TZHBgeRiaMuU5pN5zhwtzuFvfFacJs=,tag:2W1SrbbcNJN7S1Umf0WCyA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:rhSonDXNMbn/U+vU,iv:rYesfI7G+3YJDRGQ5e/dx98OtCiHTD2s5Y71Yh3W9qU=,tag:dblDRcrQekKeMMOMyziyHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jhy3kanvpc66l2usjf85sd5vq8s5ys89et0eq87zs86sd2e4643qvpspxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaR3BNaVZzQ2EyQXAvK1Fz
            YkdCelJmbU1lTGZmYjhkSW5nOTRMUk5GMVNVCjBsS1N4T3Y1YjFwQzlMaWpMRjZq
            TjM5Tkh6SGxzWVhETnVUQ3lTRnhqaEkKLS0tIHpRUDEwQndZeml4dThMaHpyTWRy
            SmNKY3VRQTk5dEYxMi9WelhVblZhdkEKy5E/w2REDThBHJRNm0n+gQIftUYtAoPU
            8jw2JzlgVwaanivzQ6bgs6QBvEoNnLcduE4kae5Mf6/o2BZarvh34g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-15T14:24:42Z"
    mac: ENC[AES256_GCM,data:I66v8Ih1swYVNRsvZkT3S0TTKOBndAzieaebcmY6K9R3WP6OlWuIMu4+uiH4vbwx2UkTvBZv2JUdi3ApCCYLJhqlQodIbH8i4kEncZNT0X+L10LQlHPfhxfK2YjvhTtLNNM9XFfjlEj7ZS/m3BBZvSq5Dnwxgu430pNLELn4Dhk=,iv:MOzrcfA4PibmvBjq+gmEUS8hbMtCum68w8+Ogq+hsu8=,tag:YfOe7rko+piwQUXbvHNMYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
