---
- hosts:
    - master
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
    - name: Print all available hostvars
      ansible.builtin.debug:
        var: hostvars
