---
- hosts:
    - master
    - worker
  become: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      pause:
        seconds: 5
  tasks:
    - name: remove /tmp/.ansible
      file:
        path: /tmp/.ansible
        state: absent
