---
# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: nfs-downloads-media
# provisioner: nfs
# reclaimPolicy: Retain
# ---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-downloads-media
  namespace: media
spec:
  storageClassName: nfs-downloads-media
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "k0.lan"
    path: "/mnt/hdd/exported/downloads"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-downloads-media
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-downloads-media
  resources:
    requests:
      storage: 1Mi
