---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs-syncthing-media
provisioner: nfs
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-syncthing-media
  # namespace: media
spec:
  storageClassName: nfs-syncthing-media
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "k0.lan"
    path: "/mnt/hdd/exported/SYNC/syncthing"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-syncthing-media
  namespace: media
spec:
  storageClassName: nfs-syncthing-media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
