---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: syncthing
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: syncthing
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      version: 3.3.0
  interval: 5m0s
  # Values link: https://github.com/k8s-at-home/charts/blob/master/charts/stable/syncthing/values.yaml
  values:
    env:
      PGID: "65534"
      PUID: "65534"
      TZ: ${TIMEZONE}
    image:
      repository: syncthing/syncthing
      tag: 1.19.0
      pullPolicy: IfNotPresent
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "folder-sync"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "syncthing.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "syncthing.${SECRET_DOMAIN}"
            secretName: "syncthing-tls"
    persistence:
      data:
        enabled: true
        existingClaim: nfs-syncthing-media
        mountPath: /var/storage
      config:
        enabled: true
        existingClaim: syncthing-config
        # config would be created in /var/syncthing/config
        # folder path should be set to /var/storage in settings
        mountPath: /var/syncthing
    service:
      # main:
      #   ports:
      #     http:
      #       port: 8384
      listen:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${METALLB_SYNCTHING_ADDR}"
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: syncthing
        ports:
          listen:
            enabled: true
            port: 22000
            protocol: TCP
            targetPort: 22000
      discovery:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${METALLB_SYNCTHING_ADDR}"
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: syncthing
        ports:
          discovery:
            enabled: true
            port: 21027
            protocol: UDP
            targetPort: 21027
