---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pyload
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: pyload
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      version: 6.2.0
  interval: 5m0s
  # Values link: https://github.com/k8s-at-home/charts/blob/master/charts/stable/pyload/values.yaml
  values:
    env:
      PGID: "1000"
      PUID: "1000"
      TZ: ${TIMEZONE}
    image:
      pullPolicy: IfNotPresent
      #repository: ghcr.io/linuxserver/pyload
      #tag: version-5de90278
      repository: ghcr.io/linuxserver/pyload-ng
      tag: version-0.5.0b3.dev24
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "weather-sunset"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "pyload.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "pyload.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: pyload-config
        # mountPath: /config
      downloads:
        enabled: true
        existingClaim: nfs-downloads-media
        # mountPath: /downloads
    service:
      main:
        ports:
          http:
            port: 8000
