---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 192.168.1.220-192.168.1.230
  METALLB_TRAEFIK_ADDR: 192.168.1.220
  METALLB_SYNCTHING_ADDR: 192.168.1.221
  LONGHORN_BACKUP_TARGET: nfs://k0.lan:/mnt/hdd/exported/LonghornBackupstore
