---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      version: 13.4.3
  interval: 5m0s
  # Values link: https://github.com/k8s-at-home/charts/blob/master/charts/stable/qbittorrent/values.yaml
  values:
    env:
      # PGID: "65534"
      # PUID: "65534"
      TZ: ${TIMEZONE}
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.4.3.1
    settings:
      automaticPortSetup: false
    service:
      main:
        ports:
          http:
            port: 8080
      bittorrent:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "cloud-download"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: &host "torrent.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    # metrics:
    #   enabled: true
    #   exporter:
    #     image:
    #       repository: ghcr.io/k8s-at-home/prometheus-qbittorrent-exporter
    #       tag: v1.2.0
    #   serviceMonitor:
    #     interval: 1m
    #     scrapeTimeout: 10s
    #   prometheusRule:
    #     enabled: true
    persistence:
      config:
        enabled: false
      #   existingClaim: qbittorrent-config
      #   mountPath: /config
      media:
        enabled: true
        existingClaim: nfs-torrent-media
        # mountPath: /media
      downloads:
        enabled: true
        existingClaim: qbittorrent-config
        # mountPath: /config
    podSecurityContext:
      supplementalGroups:
        - 5600
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 6000Mi
