---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: filebrowser
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: filebrowser
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      version: v2.18.0
  interval: 5m0s
  # Values link: https://github.com/k8s-at-home/charts/blob/master/charts/stable/filebrowser/values.yaml
  values:
    image:
      repository: filebrowser/filebrowser
      tag: v2.18.0
      pullPolicy: IfNotPresent
    env:
      TZ: ${TIMEZONE}
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "file-tree"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "filebrowser.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "filebrowser.${SECRET_DOMAIN}"
            secretName: "filebrowser-tls"
    nodeSelector:
      kubernetes.io/hostname: k0
    persistence:
      config:
        enabled: true
        existingClaim: filebrowser-config
        mountpath: /config
      data:
        enabled: true
        type: hostPath
        hostPath: ${HDD_EXPORTED_PATH}
        mountPath: /srv/data
