---
- name: Setup autofs handling nfs storage
  include_role:
    name: cmprescott.autofs
  vars:
    autofs_indirect_maps:
      - name: "auto.nfs-other"
        path: "/-"
        mark: "NFS mount with root base"
        options: "--timeout=300 --ghost"
        mounts:
          - name: "{{ hdd_export_nfs_mount }}"
            fstype: "nfs,rw,async,bg,hard,intr,tcp"
            url: "{{ nfs_server_ip }}:{{ hdd_export }}"
