---
- name: Install nfs
  include_role:
    name: geerlingguy.nfs
  vars:
    net: "192.168.1.0/24"
    opts: "(rw,all_squash,nohide,insecure,async,no_subtree_check)"
    nfs_exports:
      - "{{ hdd_export }} {{net}}{{opts}}"
