---
- name: Create a user for brother smb
  ansible.builtin.user:
    name: "{{ smb_brother_user }}"
    password_lock: yes
    state: present
    system: yes
- name: Install samba
  include_role:
    name: bertvv.samba
  vars:
    samba_mitigate_cve_2017_7494: false
    samba_users:
      - name: "{{ smb_brother_user }}"
        password: "{{ smb_brother_pass }}"
    samba_shares:
      - name: exported
        path: "{{ hdd_export }}"
        public: yes
        guest_ok: yes
        browseable: yes
        writable: no
      - name: "{{ smb_brother_share }}"
        path: "{{ smb_brother_path }}"
        browseable: no
        write_list: "{{ smb_brother_user }}"
        create_mode: 666
        directory_mode: 777
      - name: audio
        path: "{{ hdd_audio_smb }}"
        public: yes
        guest_ok: yes
        browseable: yes
        writable: no
      - name: write
        path: "{{ hdd_writable_smb }}"
        public: yes
        guest_ok: yes
        browseable: yes
        writable: yes
        create_mode: 666
        directory_mode: 777
