---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.2.3
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m
# default values: https://github.com/longhorn/longhorn/blob/master/chart/questions.yaml
# example values: https://github.com/npawelek/k8s-gitops/blob/master/cluster/core/longhorn-system/helmrelease.yaml
  values:
    persistence:
      # defaultClass: true
      defaultClassReplicaCount: 2
      # reclaimPolicy: Retain
    csi:
      attacherReplicaCount: 2
      provisionerReplicaCount: 2
      resizerReplicaCount: 2
      snapshotterReplicaCount: 2
    defaultSettings:
      # backupstorePollInterval: 300
      # backupTarget: nfs://${RACKNAS_ADDR}:/volume1/LonghornBackupstore
      # createDefaultDiskLabeledNodes: true
      # defaultDataLocality: best-effort
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
      # defaultDataPath: /var/lib/longhorn
      defaultReplicaCount: 2
      # replicaSoftAntiAffinity: false
      storageMinimalAvailablePercentage: 10
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "selfsigned-issuer"
      #   hajimari.io/enable: "true"
      #   hajimari.io/icon: "air-horn"
      #   hajimari.io/group: storage
      #   hajimari.io/appName: longhorn
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      #   traefik.ingress.kubernetes.io/router.middlewares: traefik-default-middlewares-chain@kubernetescrd
      #   traefik.ingress.kubernetes.io/router.tls.options: traefik-secure-tlsoptions@kubernetescrd
      hosts:
        - host: "longhorn.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      path: /
      host: "longhorn.${SECRET_DOMAIN}"
      tls: true
      tlsSecret: "longhorn-tls"
      # tls:
      #   - hosts:
      #       - "longhorn.${SECRET_DOMAIN}"
      #     secretName: "longhorn-tls"
