# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:hTosB8n1LkGGGoqiE5RyzpM5RB7UACJOfyTqu9+g+SgaxYQNYg==,iv:DAao84veUF8QYDlQSGAfAZD5wtB9JJrcbx5qNGgtiO0=,tag:tL5TWsJO+7FKELd8dm946g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jhy3kanvpc66l2usjf85sd5vq8s5ys89et0eq87zs86sd2e4643qvpspxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2b2NMS2ZxMm5hcXlCalZ0
            ckdKNGZtdVFNbm1lbHB5NlNrczdCeGFlNGxVCmx4T1lmN0VlZkdhOTVGblZsNDZ4
            b3ZvNE1nODRrK3lzTGNoYlZadXY4ZjgKLS0tIE05eFFEVHExWTRhSU9zTFQrMTQ5
            TFVGbVo5L1pjRUJ2cllKN3VEU0puOTgKp4JmIajlP5N+LmciXR1SZ/h4xyLV4X95
            vRcSIP3fCvjmLjaxWqRW9gkKjIEK+4FUjOA5QFb9jUFKDUQduPGddA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-16T09:42:27Z"
    mac: ENC[AES256_GCM,data:uuniFwc4CtAKO1hNMNh1yT8uCLvCULR/Z2iayZeXjYZ89A1zNVXMOl0b4h7dBzOCoYRlxanYJGPZYrveyrbcQ+6e3a2e3/nrroIrXws4o+/MLsJhZ6iOzwa384GaMZyYsxD/EZSgWxYfX0kXNtoBmmtboykOIKRdVhInFtKC0I0=,iv:qVyL6qX7If9zE9kpmwWEgYTWsM2eP7NipwgEOAnBuck=,tag:1ZaNiKTlHf+P6NOd7R26Ww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
