---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-crt
  namespace: cert-manager
spec:
  secretName: wildcard-crt-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
